# Generated by Django 4.2.24 on 2025-09-15 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "MovieID",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Movie ID",
                    ),
                ),
                ("MovieTitle", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "Actor1Name",
                    models.CharField(max_length=100, verbose_name="Lead Actor"),
                ),
                (
                    "Actor2Name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Second Actor"
                    ),
                ),
                (
                    "DirectorName",
                    models.CharField(max_length=100, verbose_name="Director"),
                ),
                (
                    "MovieGenre",
                    models.CharField(
                        choices=[
                            ("Comedy", "Comedy"),
                            ("Action", "Action"),
                            ("Drama", "Drama"),
                            ("Horror", "Horror"),
                            ("Romance", "Romance"),
                            ("Documentary", "Documentary"),
                            ("Other", "Other"),
                        ],
                        max_length=15,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "ReleaseYear",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                        verbose_name="Release Year",
                    ),
                ),
            ],
            options={
                "ordering": ["-ReleaseYear", "MovieTitle"],
            },
        ),
    ]
